### ISSUE TITLE
Increase disk space

### ISSUE THREAD

**Issue by linhlhq** [therealsaumil/armx#1]
Hi, How can I increase prebuild vmware's disk size. Thanks :)

**Comment by therealsaumil** [comment]
You can use the VMWare settings editor to change the size of the VMDK. Thereafter you can use `parted` and `resize2fs` to increase the volume after growing the VMDK disk size.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by linhlhq** [comment]
thanks :)). You can share me the configs of the devices
`D-Link DIR-880L Wi-Fi Router,
Netgear Nighthawk R6250 Wi-Fi Router,
Netgear Nighthawk R6400 Wi-Fi Router,
Cisco RV130 Wi-Fi Router`
so i can emu?

**Comment by therealsaumil** [comment]
That’s left as an exercise for emulating various devices once you obtain their firmware images.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
