### ISSUE TITLE
Issue running Docker container on setup

### ISSUE THREAD

**Issue by emandinho** [therealsaumil/armx#11]
Hi, thanks for your work in developing this environment!

I've found that on following quick install instructions, the NFS service is unable to start when running the container.

![nfs](https://user-images.githubusercontent.com/47902615/123452296-2ecf7e80-d5d6-11eb-8b21-147db2b95107.png)

OS: Kali-Linux 2020.3, running on VMware workstation

Docker version: 20.10.5+dfsg1, build 55c4c88

Please let me know if there are any systems requirements or settings I may be missing out. Many thanks

**Comment by therealsaumil** [comment]
In run-armx-docker, can you add the —privileged option and try running it again? I will see if I can replicate this issue locally.

**Comment by therealsaumil** [comment]
The issue was triggered by AppArmor. One solution is to run the docker container using the `--privileged` flag. After investigating https://dockerlabs.collabnix.com/advanced/security/apparmor/, I decided to add the flag `--security-opt apparmor=unconfined` in `run-armx-docker`.
