### ISSUE TITLE
Question on userspace / ssh command

### ISSUE THREAD

**Issue by emandinho** [therealsaumil/armx#14]
Hi,

Can you please tell me a bit more about how the 'userspace' command runs a menu immediately after ssh connection? Is it a a bashrc script running on the emulated device or some other method used to display options and start it up?

Many thanks

**Comment by therealsaumil** [comment]
It is a part of the bash profile of the HOSTFS. Launch userspace. From the menu, choose the topmost option to drop into the hostfs shell. And then check out /etc/profile.d/armx.sh - this has all the code for the userspace menu. I generated hostfs using buildroot.

**Comment by emandinho** [comment]
Thanks!
