### ISSUE TITLE
Feature Netgear Nighthawk support?

### ISSUE THREAD

**Issue by betab0t** [therealsaumil/armx#3]
Hi,

Wanted to know if you have any plans to support newer Nighthawks(R7000/R8000 etc..)?

Thanks & awesome project BTW!

**Comment by therealsaumil** [comment]
I do know that the R7000 is very similar to the R6250,R6400 (which I have both emulated). One of my students who discovered the 0day in the first place had emulated the R8xxx series. Not sure which one.

**Comment by betab0t** [comment]
Cool! Where can I find the files for R6250/R6400 to start from? seems like they were removed from the prebuilt VM...

**Comment by therealsaumil** [comment]
They weren't included in the preview VM. The screenshot which contains the R6250/R6400 emulation is from my private ARM-X installation.
