### ISSUE TITLE
NVRAM

### ISSUE THREAD

**Issue by vpistillo** [therealsaumil/armx#4]
Could you explain how to compile a custom nvram.ini.
Thanks in advanced.
VP

**Comment by therealsaumil** [comment]
You have to extract the contents of nvram from the running device. One way is by dumping the mtdblock that contains the nvram data. /proc/mtd might be of help to identify which mtdblock contains nvram. Another approach is if you have command line access via a UART (to the actual hardware of course) some firmwares provide an nvram command. Running ‘nvram show’ can also get you the nvram contents.

**Comment by vpistillo** [comment]
I have root access on the device but no mtdblock has the label nvram and there isn't the nvram command; so could you write and nvram file like example or can you help me to find what exactly I need for write a correct file nvram.ini.
Thank you very much.
VP

**Comment by therealsaumil** [comment]
Every device is different. Without a context, there's not much info I can provide.
