### ISSUE TITLE
Netgear Nighthawk R6400 Wi-Fi Router

### ISSUE THREAD

**Issue by n00biepwner** [therealsaumil/armx#6]
Hello, could you please share Netgear Nighthawk R6400 Wifi Router config files and other necessary files? Because I can not see in VM and in other files?

**Comment by credmp** [comment]
I too would like to see this added to the github repo

**Comment by therealsaumil** [comment]
They weren't included in the preview VM. The screenshot which contains the R6250/R6400 emulation is from my private ARM-X installation. The preview VM shall only contain a few examples, enough to demonstrate the features of ARM-X. You would need to populate your own firmware and work on the modifications to emulate it in ARM-X Refer the document [Emulating the Tenda AC15](https://github.com/therealsaumil/armx/blob/master/docs/emulating-tenda-ac15.md) as an example.

**Comment by credmp** [comment]
Thanks for your answer. I am checkout out the latest VM now, it looks quite good! The Archer C9 boots up nicely, however the password is not documented.

**Comment by therealsaumil** [comment]
I am sorry. The admin password for the web console is `ringzer0`
