### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MePradeep** [therealsaumil/armx#8]
![Selection_005](https://user-images.githubusercontent.com/62321654/95286566-48cb0480-0881-11eb-9f52-4c12888b0914.png)

Hi,
When i tried to setup ARM-X VM on Ubuntu 18.04 it is asking for armx login, could you please share the credentials.

**Comment by therealsaumil** [comment]
Strange. The VM should boot up directly into a GUI without requiring a password.

<img width="1280" alt="Screenshot 2021-04-07 at 13 41 17" src="https://user-images.githubusercontent.com/12379878/113833265-13a75c80-97a7-11eb-8b83-a86b0c77ea10.png">

Nonetheless, the credentials are `armx`/`ringzer0`
